### ISSUE TITLE
Search in description

### ISSUE THREAD

**Issue by RasmusGOlsen** [SystemRDL/PeakRDL-html#16]
It would be nice to extend the search option to also include search in the description field.

**Comment by amykyta3** [comment]
I've been working on this feature recently and plan to have it ready in the next release.

My primary goal has always been to ensure that the search page is responsive and fast, so for this feature special care needed to be taken to have the search page still work well. For a content-based search, theres the potential for a _massive_ amount of text to be searched (consider register maps with 100k+ nodes, each with their own descriptions). This means the exporter needs to generate a well-designed inverse keyword index that scales well and does not require a server-side back-end like most search engines do (it has been a fun challenge for me to get this implemented :smile:)

I still need to clean it up a bit and do some more involved performance tests, but the initial draft implementation has been pushed to my dev branch.
You can try it out by installing from there:
```
python3 -m pip install git+github.com:SystemRDL/PeakRDL-html.git@dev/desc-search
```

**Comment by amykyta3** [comment]
Published in `v2.3.0`

**Comment by binarybob14** [comment]
So Im on the other end of this :). I am testing this with a system of 1Million+ (more like 3M) registers and its almost unusable in its current form and consumes 8GB or so of memory since it seems to be loading all the registers into memory for search. While I would also like full text (description) search, I don't want to make the scaling problem worse.

I have tried to use tricks that I think speed things up like using arrays of components rather than individually instantiate where I can, but our address map doesn't make that possible in many cases.

Do you have any ideas or plans to make this faster? Could we provide a switch that removes search maybe at least in the interim so that I can at least load and manually click through the tool with 1M+ registers? Should I file a different github issue for my scaling problem?

**Comment by binarybob14** [comment]
sorry I just realized this was closed will open another issue.
