### ISSUE TITLE
Not able to view the generated html file

### ISSUE THREAD

**Issue by muneebullashariff** [SystemRDL/PeakRDL-html#21]
I was able to generate the html file using the script **generate_docs.py**. However, when I try to open it I am getting the following error:

Nope!
It looks like the browser you are using is not supported.
Please use a modern browser such as Firefox or Chrome.

This happens when I try to open it using Chrome, Internet Explorer 

Also, I tried to convert html to pdf, but the same issue. I am using the following for the conversion:
https://www.tutorialspoint.com/how-to-convert-html-to-pdf-using-python

Could you please take a look at this?

**Comment by amykyta3** [comment]
Internet Explorer is not supported as it is [no longer maintained by Microsoft](https://www.microsoft.com/en-us/microsoft-365/windows/end-of-ie-support).

This should work fine in Firefox, Chrome, and Microsoft Edge.
Are you getting the same error in Chrome? If so, what version of Chrome are you using?

The HTML that this tool generates contains dynamic content. I would not expect them to be able to be converted to PDF.

**Comment by muneebullashariff** [comment]
Yes, I am facing the same error in Chrome. 

Google Chrome is up to date
Version 83.0.4103.106 (Official Build) (64-bit)

**Comment by muneebullashariff** [comment]
Closed by mistake

**Comment by muneebullashariff** [comment]
> The HTML that this tool generates contains dynamic content. I would not expect them to be able to be converted to PDF.

But at least the static contents on the page should be converted to pdf, right?

**Comment by kevbroch** [comment]
@muneebullashariff : For me because of default security setting in Chrome/Brave I see the following:

```
Oops!
Your browser's security policy prevents this page from loading properly when using the 'file://' protocol.

If possible, host this page on a web server and access using the 'http://' protocol.

Other workarounds
Firefox
Change your Firefox security settings:

In your address bar, type about:config
Set privacy.file_unique_origin to false
For more details, see: Reason: CORS request not HTTP
Chrome
Launch your Chrome session using the --allow-file-access-from-files command line switch

Python http server
Host using a temporary Python http server:

python -m http.server
```

When I open it in Firefox, it works as expected.

**Comment by amykyta3** [comment]
@muneebullashariff: Are you getting the "Oops!" error in Chrome that @kevbroch pasted? Or are you seeing the "Nope!" message?

If its the "Nope!" message, then I'm surprised since you have the latest version of Chrome and I also use the tool in Chrome regularly with no issues. Please double-check the error message and follow the recommendations in the error text. Due to how page content is dynamically loaded, I'd recommend hosting the page. I usually run a mini python webserver when testing things out locally.

Regarding exporting to PDF, it really depends on the tool being used. I could see the dynamic page loading cause issues if doing it via python. For what its worth, I was able to "Print to PDF" directly from my browser and it kinda worked.
