### ISSUE TITLE
Search by property

### ISSUE THREAD

**Issue by markcohen32** [SystemRDL/PeakRDL-html#29]
Hi, is there an option to search for a register with certain property/property value in the search bar? 
If not, is it possible to add such feature?

Thanks

**Comment by amykyta3** [comment]
Not currently.
I'll have to think about how to implement this without hurting the performance of the existing search. 
The current search algorithm is structured so that it scales decently even for huge register maps with tens of thousands of nodes. Similar to #16, this change could represent a _significant_ increase in the amount of data that the client-side browser would have to load. I might be able to index the information in a way that minimizes fetching, but it gets tricky.

**Comment by markcohen32** [comment]
Thanks :)

**Comment by amykyta3** [comment]
Be sure to check out #16. I have a draft implementation of the content-based search if you want to try it out.
