### ISSUE TITLE
Register arrays showing blank square brackets in left-side TOC

### ISSUE THREAD

**Issue by JacobEFO** [SystemRDL/PeakRDL-html#40]
Hi,

First thanks for this wonderful tool, makes handling documentation of registers a breeze!

However, I found one nuissance/bug. If I create an array of registers, say 8, in the TOC it shows up as `PROM[]`. It would be highly useful if it could be something alla `PROM[Addr:Addr-8]`

See the bug:
<img width="109" alt="image" src="https://github.com/SystemRDL/PeakRDL-html/assets/22648097/3cee72e5-5a5f-442c-b03f-66cee5e15d1d">

Minimum working example:
```
reg {
    name = "PROM";

    field {
        name = "Value";
        desc = "";
        sw=rw;
    } TBD[8] = 0xFF;
} PROM[8];
```

**Comment by amykyta3** [comment]
The empty brackets are intentional to denote that the object is an array, but I can see how adding more information could be useful.

I do not understand your notation of `PROM[Addr:Addr-8]`, but what if I add an option to show the array dimensions? Something like: `PROM[8]`. However my fear would be that it could be misinterpreted as an array index rather than a dimension - this  is why I intentionally left them as empty braces in the current implementation: `PROM[]`
